services:
  sup_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sup_app_container
    ports:
      - "1850:1850"
    volumes:
      # Пример: подключаем локальную директорию /app, если хотим видеть изменения в реальном времени
      # - .:/app
      - ./storage:/app/storage
    restart: unless-stopped