services:
  sup_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sup_app_container
    ports:
      - "1850:1850"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped